openai_api_key: "sk-c8MPNGu3mlLbIM2fVdKR8W8omgLShKZG0QzzueupayT3BlbkFJvhLCnBjCWSJToL_tRfFw8nX1Zm7hDF0rhGa7T-lB8A"
telegram_token: "7869120128:AAF0cKunBaxTIwHLYJjykhcm890TCPf7gJg"
allowed_telegram_usernames: []  # if empty, the bot is available to anyone. pass a username string to allow it and/or user ids as positive integers and/or channel ids as negative integers
new_dialog_timeout: 600  # new dialog starts after timeout (in seconds)
return_n_generated_images: 1
n_chat_modes_per_page: 5
image_size: "512x512" # the image size for image generation. Generated images can have a size of 256x256, 512x512, or 1024x1024 pixels. Smaller sizes are faster to generate.
enable_message_streaming: true  # if set, messages will be shown to user word-by-word
